- hosts: webapps
  become: yes
  roles:
    - ./../roles/docker
    - ./../roles/docker_containers
  vars:
    root_dir: "./../../../"
    dest_dir: /var/www
    docker_app_name: app
  tasks:
    - name: Update Nginx Default Homepage
      template:
        dest: /var/www/html/index.nginx-debian.html
        src: ./../templates/nginx.default.html
  tasks:
    - name: Setup /var/www
      file:
        path: "{{ dest_dir }}"
        state: directory
        mode: 0755
    - name: Copy FOlders
      copy:
        src: "{{ root_dir }}/src"
        dest: "{{ dest_dir }}"
      register: app_folder
    - copy:
        src: "{{ root_dir }}/{{ item }}"
        dest: "{{ dest_dir }}"
      with_items:
        - Dockerfile
        - requirements.txt
        - entrypoint.sh
    - name: Trigger Build and Run
      shell: echo "Running Build"
      notify:
        - docker build
        - docker stop containers
        - docker remove containers
        - docker run app
